services:
  tagbot-db:
    container_name: tagbot-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tagbot-app:
    image: tagbot_image:latest
    container_name: tagbot-app
    build: .
    restart: always
    depends_on:
      - tagbot-db
    env_file:
      - .env

volumes:
  postgres_data: